#Python Basics - Pandas DataFrame

**Question 1 :  Write a Python program to check whether a number is even or odd using conditional statements.**

In [1]:
num = 7

if num % 2 == 0:
    print("Even number")
else:
    print("Odd number")

Odd number


**Question 2 : Write a Python program to count how many times a number appears in a list.**

**Example List**

**[2,3,4,2,5,2]**

In [2]:
numbers = [2, 3, 4, 2, 5, 2]

count = numbers.count(2)

print("Number of times 2 appears:", count)

Number of times 2 appears: 3


**Question 3 :  Generate an array from 1 to 20 with step size 2.**

In [3]:
import numpy as np

array = np.arange(1, 21, 2)

print(array)

[ 1  3  5  7  9 11 13 15 17 19]


**Question 4 : Create a new column called Revenue, where:  Revenue = Quantity × Price  Display the updated dataset with the new column.**

In [5]:
df["Revenue"] = df["Quantity"] * df["Price"]

print(df)

   Transaction ID Customer ID Product Category  Quantity   Price        Date  \
0            T001        C015            Books       7.0   167.0  02-02-2023   
1            T002        C004             Toys       4.0   374.0  17-02-2023   
2            T003        C033        Furniture       8.0  1059.0  17-05-2024   
3            T004        C047        Groceries       5.0   304.0  11-02-2024   
4            T005        C022            Books       7.0   282.0  27-07-2024   
..            ...         ...              ...       ...     ...         ...   
95           T096        C036        Furniture      10.0  2901.0  08-08-2023   
96           T097        C021         Clothing       9.0  1077.0  19-07-2024   
97           T098        C015         Clothing       7.0   643.0  13-08-2023   
98           T099        C005        Groceries       9.0   429.0  20-01-2024   
99           T100        C010        Furniture       8.0  1183.0  07-02-2024   

   Region  Revenue  
0   North   1169.0

**Question 5 : Convert a 1D array into 2x3 matrix:  arr = np.array([1,2,3,4,5,6]).**

In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

matrix = arr.reshape(2, 3)

print(matrix)

[[1 2 3]
 [4 5 6]]


**Question 6 : Slicing Data**

**1. Select first 10 rows**

**2. Select only "Product Category" and "Quantity" columns**

In [7]:
#Select first 10 rows

print(df.head(10))

  Transaction ID Customer ID Product Category  Quantity   Price        Date  \
0           T001        C015            Books       7.0   167.0  02-02-2023   
1           T002        C004             Toys       4.0   374.0  17-02-2023   
2           T003        C033        Furniture       8.0  1059.0  17-05-2024   
3           T004        C047        Groceries       5.0   304.0  11-02-2024   
4           T005        C022            Books       7.0   282.0  27-07-2024   
5           T006        C042      Electronics      10.0   866.0  28-12-2024   
6           T007        C022        Furniture       3.0  2340.0  09-04-2023   
7           T008        C023         Clothing       7.0   881.0  14-11-2024   
8           T009        C008      Electronics       8.0   780.0  26-12-2024   
9           T010        C003        Furniture       5.0  1617.0  30-06-2024   

  Region  Revenue  
0  North   1169.0  
1  South   1496.0  
2  South   8472.0  
3  South   1520.0  
4   West   1974.0  
5   West  

In [8]:
#Select only "Product Category" and "Quantity" columns

print(df[["Product Category", "Quantity"]])

   Product Category  Quantity
0             Books       7.0
1              Toys       4.0
2         Furniture       8.0
3         Groceries       5.0
4             Books       7.0
..              ...       ...
95        Furniture      10.0
96         Clothing       9.0
97         Clothing       7.0
98        Groceries       9.0
99        Furniture       8.0

[100 rows x 2 columns]


**Question 7 : Find all records where:**

 - **Region = "South" and Quantity > 2**

In [10]:
result = df[(df["Region"] == "South") &

(df["Quantity"] > 2)]

print(result)

   Transaction ID Customer ID Product Category  Quantity   Price        Date  \
1            T002        C004             Toys       4.0   374.0  17-02-2023   
2            T003        C033        Furniture       8.0  1059.0  17-05-2024   
3            T004        C047        Groceries       5.0   304.0  11-02-2024   
24           T025        C022      Electronics       9.0   751.0  29-08-2023   
32           T033        C022        Furniture       5.0  2707.0  24-06-2024   
39           T040        C004             Toys       4.0   778.0  31-07-2024   
40           T041        C041             Toys       9.0     NaN  12-11-2024   
44           T045        C049         Clothing      10.0   934.0  28-01-2023   
55           T056        C010            Books       4.0   434.0  13-08-2023   
60           T061        C049           Sports       4.0   990.0  19-09-2024   
61           T062        C028         Clothing       6.0  1323.0  16-09-2023   
69           T070        C041      Elect

**Question 8 : Display:**

**1. The first 10 rows of the dataset.**

**2. Rows 15 to 25.**

In [11]:
#The first 10 rows of the dataset.

print(df.head(10))

  Transaction ID Customer ID Product Category  Quantity   Price        Date  \
0           T001        C015            Books       7.0   167.0  02-02-2023   
1           T002        C004             Toys       4.0   374.0  17-02-2023   
2           T003        C033        Furniture       8.0  1059.0  17-05-2024   
3           T004        C047        Groceries       5.0   304.0  11-02-2024   
4           T005        C022            Books       7.0   282.0  27-07-2024   
5           T006        C042      Electronics      10.0   866.0  28-12-2024   
6           T007        C022        Furniture       3.0  2340.0  09-04-2023   
7           T008        C023         Clothing       7.0   881.0  14-11-2024   
8           T009        C008      Electronics       8.0   780.0  26-12-2024   
9           T010        C003        Furniture       5.0  1617.0  30-06-2024   

  Region  Revenue  
0  North   1169.0  
1  South   1496.0  
2  South   8472.0  
3  South   1520.0  
4   West   1974.0  
5   West  

In [12]:
#Rows 15 to 25.

print(df.iloc[15:26])

   Transaction ID Customer ID Product Category  Quantity   Price        Date  \
15           T016        C029         Clothing       5.0   639.0  17-05-2024   
16           T017        C004             Toys       2.0   423.0  02-02-2024   
17           T018        C039             Toys       8.0     NaN  28-01-2024   
18           T019        C022           Sports       6.0  1328.0  26-07-2023   
19           T020        C045             Toys       2.0   962.0  15-01-2023   
20           T021        C043            Books       NaN   516.0  07-07-2024   
21           T022        C042      Electronics       1.0  1971.0  05-04-2024   
22           T023        C015           Beauty      10.0   174.0  21-11-2024   
23           T024        C012         Clothing       6.0   236.0  28-07-2024   
24           T025        C022      Electronics       9.0   751.0  29-08-2023   
25           T026        C023           Sports       1.0   902.0  17-07-2024   

   Region  Revenue  
15  North   3195.0

**Question 9 : Create a random array of 10 numbers and:**

 - **Find max and min**

 - **Sort the array**

In [14]:
import numpy as np

arr = np.random.randint(1, 100, 10)

print("Random Array:", arr)

print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))

print("Sorted Array:", np.sort(arr))

Random Array: [61 68 74  1 61 69  2 23 92 14]
Maximum: 92
Minimum: 1
Sorted Array: [ 1  2 14 23 61 61 68 69 74 92]


**Question 10 : Replace all even numbers with 0:**

**arr = np.array([1,2,3,4,5,6])**

In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

arr[arr % 2 == 0] = 0

print(arr)

[1 0 3 0 5 0]


$$
***
$$